---
- name: copy dotfiles to dest home
  copy: src="../../../../dotfiles" dest="~vagrant" owner=vagrant group=vagrant mode="u=rwx,g=r,o=r"

- name: Create symlinks
  file:
    src: ~vagrant/dotfiles/{{ item }}
    dest: ~vagrant/{{ item }}
    state: link
    force: yes
  with_items:
    - .tmux.conf
    - .zshrc
    - .vimrc
