---
- name: copy dotfiles to dest home
  copy: src="../../../../dotfiles" dest="~" owner={{ ansible_env.SUDO_USER }}  group={{ ansible_env.SUDO_USER }}  mode="u=rwx,g=r,o=r"

- name: Create symlinks
  file:
    src: ~/dotfiles/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .tmux.conf
    - .zshrc
    - .vimrc
