---
- name: requires install
  yum: name={{ item }} state=latest
  with_items:
    - gcc
    - git
    - mercurial
    - ncurses-devel
    - lua
    - lua-devel 
    - perl
    - perl-devel
    - perl-ExtUtils-Embed
    - python
    - python-devel
    - libselinux-python

- name: Install vim by yum
  yum: name=vim state=present

- name: copy .vimrc file to vagrant home
  #ホストOSの.vimrcをゲストOSにコピー
  copy: src=~/.vimrc dest=~vagrant/.vimrc owner=vagrant group=vagrant mode="u=rw,g=r,o=r"
  #provisioning/roles/vim/.vimrcをゲストOSにコピー
  #copy: src=../.vimrc dest=~vagrant/.vimrc owner=vagrant group=vagrant mode="u=rw,g=r,o=r"
