# master playbook
---

# centos6 specific tasks
- include: centos6.yml
  when: 
   - ansible_distribution == "CentOS"
   - ansible_distribution_major_version == "6"

# centos7 specific tasks
- include: centos7.yml
  when:
   - ansible_distribution == "CentOS"
   - ansible_distribution_major_version == "7" 

#Ubuntu specific tasks
- include: ubuntu16.yml
  when:
   - ansible_distribution == "Ubuntu"
   - ansible_distribution_major_version == "16"
