---
- name: install yum-utils
  yum: 
    name: yum-utils 
    state: present

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present
  become: yes

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0
  become: yes

- name: Install Docker package
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    groups: docker
    append: yes
  become: yes

- name: Ensure docker service is enabled
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: +x
  become: yes
