---
- name: vim requires install by yum
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - git
      - python
      - python-devel
      - libselinux-python

- name: install vim by yum
  yum:
    name: vim
    state: latest
  
